#!/bin/bash
# Use the data from the US National Weather Service to view the radar for weather in your area
# Intended for US only

# Title
TWR="Weather Radar"

usage() {
    cat <<USAGE

    Usage: $0 [-r radar] [-n] [-w] [-t] [-f]

    Options:
        -r, --radar:       Show regional radar
        -n, --national:     Show national weather graph
        -f, --forecast:     Show detailed regional forecast map for region
        -w, --weather:      Show weather forcast for region
        -t, --temps:        Show basic temperature forcast for region
USAGE
    exit 1
}

if [ $# -eq 0 ]; then
    usage
    exit 1
fi

while [ "$1" != "" ]; do
    case $1 in
    n | -n | --national | national)
        notify-send "$TWR" "Opening national radar."
        mpv --title="$TWR" --cache=yes --loop-file=inf "https://www.wpc.ncep.noaa.gov/noaa/noaad1.gif"
        ;;
    r | -r | --radar)
        shift
        TAG=$1
        if [[ $TAG == "" ]]; then
            echo "You must provide a tag when using the -r flag, please try again...";
            exit 1;
        fi
        notify-send "$TWR" "Opening radar for $TAG region."
        mpv --title="$TWR" --cache=yes --loop-file=inf "https://radar.weather.gov/ridge/lite/K${TAG^^}_loop.gif"
        # mpv --title="$TWR" --cache=yes --loop-file=inf "https://radar.weather.gov/ridge/lite/N0R/${TAG^^}_loop.gif"
        ;;
    w | -w | --weather)
        shift
        TAG=$1
        if [[ $TAG == "" ]]; then
            echo "You must provide a tag when using the -w flag, please try again...";
            exit 1;
        fi
        notify-send "$TWR" "Opening radar for $TAG region."
        mpv --title="$TWR" --cache=yes --loop-file=inf "https://www.weather.gov/images/${TAG,,}/graphicast/image4.png"
        ;;
    f | -f | --forcast)
        shift
        TAG=$1
        if [[ $TAG == "" ]]; then
            echo "You must provide a tag when using the -f flag, please try again...";
            exit 1;
        fi
        notify-send "$TWR" "Opening radar for $TAG region."
        mpv --title="$TWR" --cache=yes --loop-file=inf "https://www.weather.gov/images/${TAG,,}/graphicast/image1.png"
        ;;
    t | -t | --temps)
        shift
        TAG=$1
        if [[ $TAG == "" ]]; then
            echo "You must provide a tag when using the -t flag, please try again...";
            exit 1;
        fi
        mpv --title="$TWR" --cache=yes --loop-file=inf "https://graphical.weather.gov/images/${TAG,,}/T2_${TAG,,}.png"
        ;;
    h | help | -h | --help)
        usage
        ;;
    *)
        usage
        exit 1
        ;;
    esac
    shift
done

